### ISSUE TITLE
Cache documentation

### ISSUE THREAD

**Issue by RLejolivet** [blossom-project/blossom#115]
Some documentation about the BlossomCache usage would be nice.

- Annotation usage examples
- Manual usage examples
- Specification string documentation (`expireAfterWrite` etc syntax... I was only able to find documentation on the api functions, but not on the equivalent string syntax)

**Comment by mgargadennec** [comment]
We should link to the relevant Spring Cache / JSR 107 / Caffeine documentation.

BlossomCache  / BlossomCacheResolver / BlossomCacheManager/ CacheConfig / CacheConfigBuilder should indeed be documented !

**Comment by mgargadennec** [comment]
Documentation added to initializr.
