### ISSUE TITLE
User impersonation

### ISSUE THREAD

**Issue by RLejolivet** [blossom-project/blossom#143]
Allow BO users with certain rights (user administration ? or a brand new "impersonation" right ?) to impersonate other BO users : easily check what they see / have access to ; and change password if email access is blocked.

For audit purposes, all actions taken while impersonating should mention both the impersonated account, and impersonating account.

**Comment by mgargadennec** [comment]
Implementation could use this approach : [https://www.dontpanicblog.co.uk/2015/08/20/user-impersonation-with-spring-security/](https://www.dontpanicblog.co.uk/2015/08/20/user-impersonation-with-spring-security/)
