### ISSUE TITLE
Allow the use of InternetAddress instead of String for emails

### ISSUE THREAD

**Issue by abenoit-reeliant** [blossom-project/blossom#159]
Blossom's MailSender only allows the use of String objects for sender and recipients. 
This means that it cannot use a combination of name and email address using InternetAddress objects.

Alternative methods using InternetAddress instead of String should be available.

**Comment by mgargadennec** [comment]
I'm considering replacing all methods with `InternetAdress` in release 1.1.0.

Migration should be easy for actual live usage (`new InternetAdress(mailStr)` )

Should I keep actual methods during this version, marking them as deprecated?

**Comment by abenoit-reeliant** [comment]
I think it would be best to keep the old methods as deprecated (and as wrappers using the InternetAddress methods behind the scenes) for at least one version to give users time to migrate.

**Comment by mgargadennec** [comment]
That's what I've done ;-)

**Comment by mgargadennec** [comment]
I also added a fromName properties on `MailsenderProperties` which allowed me to use InternetAddress on the "from" field of the mails.
