### ISSUE TITLE
Mail: better default

### ISSUE THREAD

**Issue by cardiweb** [blossom-project/blossom#180]
There is no default configuration for mail.
In most case, java smtp server will be localhost.
And if the not true, there will be stack trace in log more visible than actual : 

```2018-07-23 13:56:56.576  INFO 14553 --- [nio-8004-exec-3] c.b.c.c.utils.mail.NoopMailSenderImpl    : A mail with recipient(s) '[mbaroukh@cardiweb.com]' and subject 'activation.subject' was not sent because no java mail sender is configured```

This log is only at INFO level, not ERROR.
(also, note the subject).

Another option is, by default, to log mail content, assuming we are on the developer desktop.

**Comment by cardiweb** [comment]
> I agree to have better logs for email but i find it weird to assume it's ERROR level.
The application tried to send a mail, can't, and it's not really a problem ???

**Comment by mgargadennec** [comment]
Nope, more likely a WARN.
It's more like : the application tried to send an email, but the developer forgot to tell the prod team to add configuration, so the application warns that no email has been sent.

**Comment by mbaroukh** [comment]
ok, as you wan't. Fixed log level here : 
https://github.com/blossom-project/blossom/pull/192

We will fix the remaining on our side.
