### ISSUE TITLE
War deployment

### ISSUE THREAD

**Issue by lperrod** [blossom-project/blossom#55]
Provide some documentation in order to explain how a user can use blossom as a war.
(What main class create, whate changes to make in the pom : 

`
<packaging>war</packaging>, 
<properties>
...
<start-class>MyMainClass</start-class>
...
</properties>
<dependencies>
...
<dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-tomcat</artifactId>
	        <scope>provided</scope>
	    </dependency>
...
</dependencies>
`

`
@EnableBlossom
@SpringBootApplication
@EnableJpaRepositories
@EntityScan
 public class MyMainClass extends SpringBootServletInitializer {

  @Override
  protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
    return application.sources(MyMainClass .class);
  }

  public static void main(String[] args) throws Exception {
    SpringApplication.run(MyMainClass .class, args);
  }

}
`

And also find a way to make the war less fat (today it reaches 100Mo)

**Comment by mgargadennec** [comment]
We should provide a jar/war option in the Initializr and document it instead !

Go @lperrod  ! :-D

**Comment by lperrod** [comment]
I will think about it, still there is the war size issue
