### ISSUE TITLE
Protect brute-force attemps on BO users

### ISSUE THREAD

**Issue by RLejolivet** [blossom-project/blossom#58]
I may have missed it, but there doesn't seem to be any lockout mechanism to prevent brute-force checking passwords for BO users:

- CurrentUser always calls `super` with all lockout flags as default
- CurrentUserDetailsServiceImpl always returns needed information as well

Should we add basic rules, such as:

- no more than 5 failures per IP per account per 24 hours
- no more than 15 failures per IP across all accounts per 24 hours

Numbers can obviously be tweaked (configurable?)

**Comment by mgargadennec** [comment]
We could use a specific AuthenticationProvider which stores a number of failures for a given IP and account and then evict them periodically.

**Comment by mgargadennec** [comment]
Done with a default 10 login attemps, then the tuple idenfier/ip is locked for 24 hours.
A new admin interface is available in the "System -> Sessions" menu.
