### ISSUE TITLE
Groups with the same name

### ISSUE THREAD

**Issue by pcrouillere** [blossom-project/blossom#74]
# What I See

I am not sure that's an issue but i can create a lot of groups with the same name. I think its not a good idea but .. your choice! :) 

# How to do it ?
1. Admin > Groups > "+" > Add one groups "aztz" > Save
2. Create another group with the same name
3. Tada ! 

# What I think we should have
1. No pb
2. Error "You already have a group with this name" (or something like that)

**Comment by mgargadennec** [comment]
Added user email and identifier 
Added toaster notifications on errors.
Added global errors on validation failures.
